-- this is copy of crebas_hsqldb.sql, that shoudl be placed in home folder before first start
create cached table dbversion
(
    dbversion_id    int generated by default as identity (start with 1),
    version_id      int not null,
    version         varchar(12),
    constraint dbversion_pk primary key (dbversion_id)
);

insert into dbversion values(1,1,'0.1');

create cached table picture
(
    picture_id   int generated by default as identity (start with 1),
    picture      other,
    constraint picture_pk primary key (picture_id)
);

create cached table user
(
    user_id     int generated by default as identity (start with 1),
    first_name  varchar(32) not null,
    last_name   varchar(32) not null,
    initials    char(2) not null,
    login       varchar(32),
    passwd      varchar(32),
    is_admin    bit default 0,
    photo       other,
    constraint user_pk primary key (user_id)
);

insert into user (user_id,first_name,last_name,initials,login,passwd,is_admin) values (1,'Admin','Adminson','AA','admin','admin',1);
insert into user (user_id,first_name,last_name,initials,login,passwd,is_admin) values (2,'Nick','Mukhin','NA','nick','tainam',1);
insert into user (user_id,first_name,last_name,initials,login,passwd,is_admin) values (3,'Dick','Kikstra','DK','dick','kikstra',1);

create cached table klant
(
    klant_id      int generated by default as identity (start with 1),
    aanhef        varchar(32) not null,
    voorletters   varchar(32) not null,
    tussenvoegsel varchar(32) not null,
    achternaam    varchar(32) not null,
    adres         varchar(64) not null,
    huisnummer    varchar(32) not null,
    postcode      varchar(16),
    plaats        varchar(32),
    land          varchar(32),
    geboortedatum date,
    telefoon      varchar(32),
    mobiel        varchar(32),
    email         varchar(64),
    constraint klant_pk primary key (klant_id)
);

insert into klant (klant_id,aanhef,voorletters,tussenvoegsel,achternaam,adres,huisnummer)
values(1,'De heer','S.','de','Vries','Hermestraat','16');

insert into klant (klant_id,aanhef,voorletters,tussenvoegsel,achternaam,adres,huisnummer)
values(2,'De heer','Nickolay','Alexandrovich','Mukhin','Konstantina Velikogo','18/73');

INSERT INTO "PUBLIC"."KLANT"
( klant_id,"AANHEF", "VOORLETTERS", "TUSSENVOEGSEL", "ACHTERNAAM", "ADRES", "HUISNUMMER", "POSTCODE", "PLAATS", "LAND", "GEBOORTEDATUM", "TELEFOON", "MOBIEL", "EMAIL" )
VALUES ( 3,'AA', 'VV', 'TT', 'CC', 'DD', 'UU', 'CCD', 'PL', 'Russia','1925-01-01', '999', '888', 'nm60@mail.ru');

create cached table brilvoorschrift
(
    brilvoorschrift_id  int generated by default as identity (start with 1),
    klant_id            int not null,
    od_sph              decimal(4,2),
    od_cyl              decimal(3,2),
    od_as               tinyint,
    od_add              decimal(3,2),
    od_nabil            decimal(3,2),
    od_pr               tinyint,
    od_basis            smallint,
    od_pr1              tinyint,
    od_basis1           smallint,
    od_vis              decimal(2,1),
    od_pddn             varchar(16),
    od_lh               tinyint,
    od_ha               tinyint,
    od_iod              tinyint,
    os_sph              decimal(4,2),
    os_cyl              decimal(3,2),
    os_as               tinyint,
    os_add              decimal(3,2),
    os_nabil            decimal(3,2),
    os_pr               tinyint,
    os_basis            smallint,
    os_pr1              tinyint,
    os_basis1           smallint,
    os_vis              decimal(2,1),
    os_pddn             varchar(16),
    os_lh               tinyint,
    os_ha               tinyint,
    os_iod              tinyint,
    oogmeting_door      varchar(64),
    datum_refractie     date,
    anamnese            clob,
    constraint brilvoorschrift_pk primary key (brilvoorschrift_id),
    constraint brilvoorschrift_klant_fk foreign key (klant_id) references klant
);

create cached table verkoop
(
    verkoop_id     int generated by default as identity (start with 1),
    klant_id       int not null,
    r_leverancier  varchar(32),
    l_reverancier  varchar(32),
    r_type_glas    varchar(32),
    l_type_glas    varchar(32),
    r_coating      varchar(32),
    l_coating      varchar(32),
    r_kleur_glazen varchar(32),
    l_kleur_glazen varchar(32),
    r_diameter     tinyint,
    l_diameter     tinyint,
    r_prijs_glas   decimal(6,2),
    l_prijs_glas   decimal(6,2),
    r_btw          decimal(5,2),
    l_btw          decimal(5,2),
    montuur_merk   varchar(32),
    montuur_model  varchar(32),
    montuur_kleur  varchar(32),
    montuur_maat   varchar(32),
    montuur_prijs  decimal(6,2),
    montuur_btw    decimal(5,2),
    soort_glas     varchar(32),
    montuur_type   varchar(32),
    materiaal      varchar(32),
    korting        decimal(6,2),
    totaal         decimal(6,2),
    total_btw      decimal(5,2),
    verkoopdatum   date not null,
    diverse        varchar(32),
    id_montuur     varchar(32),
    breedte        tinyint,
    hoogte         tinyint,
    neusmaat       tinyint,
    soort_glas     varchar(32),
    diverse_prijs  decimal(6,2),
    diverse_btw    decimal(5,2),
    constraint verkoop_pk primary key (verkoop_id),
    constraint verkoop_klant_fk foreign key (klant_id) references klant
);

alter table verkoop add diverse varchar(32);
alter table verkoop add id_montuur varchar(32);
alter table verkoop add breedte tinyint;
alter table verkoop add hoogte  tinyint;
alter table verkoop add neusmaat tinyint;
alter table verkoop add soort_glas varchar(32);
alter table verkoop add diverse_prijs decimal(6,2);
alter table verkoop add diverse_btw decimal(5,2);

alter table verkoop alter column diverse_btw decimal(5,2);
alter table verkoop alter column total_btw decimal(5,2);

