create cached table dbversion
(
    dbversion_id    int generated by default as identity (start with 1),
    version_id      int not null,
    version         varchar(12),
    constraint dbversion_pk primary key (dbversion_id)
);

insert into dbversion values(1,1,'0.1');

create cached table picture
(
    picture_id   int generated by default as identity (start with 1),
    picture      other,
    constraint picture_pk primary key (picture_id)
);

create cached table user
(
    user_id     int generated by default as identity (start with 1),
    first_name  varchar(32) not null,
    last_name   varchar(32) not null,
    initials    char(2) not null,
    login       varchar(32),
    passwd      varchar(32),
    is_admin    bit default 0,
    photo       other,
    constraint user_pk primary key (user_id)
);

insert into user (first_name,last_name,initials,login,password,is_admin) values ('Admin','Adminson','AA','admin','admin',1);
insert into user (first_name,last_name,initials,login,password,is_admin) values ('Nick','Mukhin','NA','nick','tainam',1);
insert into user (first_name,last_name,initials,login,password,is_admin) values ('Dick','Kikstra','DK','dick','kikstra',1);
